#
# Auto-generated file.
# DO NOT EDIT
# Edit generate.pl in the main folder to make changes here
#

MODULE = CoreWebView2	PACKAGE = CoreWebView2

PROTOTYPES: DISABLE

#
# HRESULT
#

SV*
S_OK()
	CODE:
		RETVAL = newSVuv((UV)S_OK);
		dualize(RETVAL, "S_OK");
	OUTPUT:
		RETVAL

SV*
S_FALSE()
	CODE:
		RETVAL = newSVuv((UV)S_FALSE);
		dualize(RETVAL, "S_FALSE");
	OUTPUT:
		RETVAL

SV*
E_ABORT()
	CODE:
		RETVAL = newSVuv((UV)E_ABORT);
		dualize(RETVAL, "E_ABORT");
	OUTPUT:
		RETVAL

SV*
E_ACCESSDENIED()
	CODE:
		RETVAL = newSVuv((UV)E_ACCESSDENIED);
		dualize(RETVAL, "E_ACCESSDENIED");
	OUTPUT:
		RETVAL

SV*
E_FAIL()
	CODE:
		RETVAL = newSVuv((UV)E_FAIL);
		dualize(RETVAL, "E_FAIL");
	OUTPUT:
		RETVAL

SV*
E_HANDLE()
	CODE:
		RETVAL = newSVuv((UV)E_HANDLE);
		dualize(RETVAL, "E_HANDLE");
	OUTPUT:
		RETVAL

SV*
E_INVALIDARG()
	CODE:
		RETVAL = newSVuv((UV)E_INVALIDARG);
		dualize(RETVAL, "E_INVALIDARG");
	OUTPUT:
		RETVAL

SV*
E_NOINTERFACE()
	CODE:
		RETVAL = newSVuv((UV)E_NOINTERFACE);
		dualize(RETVAL, "E_NOINTERFACE");
	OUTPUT:
		RETVAL

SV*
E_NOTIMPL()
	CODE:
		RETVAL = newSVuv((UV)E_NOTIMPL);
		dualize(RETVAL, "E_NOTIMPL");
	OUTPUT:
		RETVAL

SV*
E_OUTOFMEMORY()
	CODE:
		RETVAL = newSVuv((UV)E_OUTOFMEMORY);
		dualize(RETVAL, "E_OUTOFMEMORY");
	OUTPUT:
		RETVAL

SV*
E_POINTER()
	CODE:
		RETVAL = newSVuv((UV)E_POINTER);
		dualize(RETVAL, "E_POINTER");
	OUTPUT:
		RETVAL

SV*
E_UNEXPECTED()
	CODE:
		RETVAL = newSVuv((UV)E_UNEXPECTED);
		dualize(RETVAL, "E_UNEXPECTED");
	OUTPUT:
		RETVAL

SV*
E_PENDING()
	CODE:
		RETVAL = newSVuv((UV)E_PENDING);
		dualize(RETVAL, "E_PENDING");
	OUTPUT:
		RETVAL

#
# DISPATCH
#

SV*
DISPATCH_METHOD()
	CODE:
		RETVAL = newSVuv((UV)DISPATCH_METHOD);
		dualize(RETVAL, "DISPATCH_METHOD");
	OUTPUT:
		RETVAL

SV*
DISPATCH_PROPERTYGET()
	CODE:
		RETVAL = newSVuv((UV)DISPATCH_PROPERTYGET);
		dualize(RETVAL, "DISPATCH_PROPERTYGET");
	OUTPUT:
		RETVAL

SV*
DISPATCH_PROPERTYPUT()
	CODE:
		RETVAL = newSVuv((UV)DISPATCH_PROPERTYPUT);
		dualize(RETVAL, "DISPATCH_PROPERTYPUT");
	OUTPUT:
		RETVAL

SV*
DISPATCH_PROPERTYPUTREF()
	CODE:
		RETVAL = newSVuv((UV)DISPATCH_PROPERTYPUTREF);
		dualize(RETVAL, "DISPATCH_PROPERTYPUTREF");
	OUTPUT:
		RETVAL

#
# CAPTURE_PREVIEW_IMAGE_FORMAT
#

SV*
CAPTURE_PREVIEW_IMAGE_FORMAT_PNG()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_CAPTURE_PREVIEW_IMAGE_FORMAT_PNG);
		dualize(RETVAL, "COREWEBVIEW2_CAPTURE_PREVIEW_IMAGE_FORMAT_PNG");
	OUTPUT:
		RETVAL

SV*
CAPTURE_PREVIEW_IMAGE_FORMAT_JPEG()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_CAPTURE_PREVIEW_IMAGE_FORMAT_JPEG);
		dualize(RETVAL, "COREWEBVIEW2_CAPTURE_PREVIEW_IMAGE_FORMAT_JPEG");
	OUTPUT:
		RETVAL

#
# COOKIE_SAME_SITE_KIND
#

SV*
COOKIE_SAME_SITE_KIND_NONE()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_COOKIE_SAME_SITE_KIND_NONE);
		dualize(RETVAL, "COREWEBVIEW2_COOKIE_SAME_SITE_KIND_NONE");
	OUTPUT:
		RETVAL

SV*
COOKIE_SAME_SITE_KIND_LAX()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_COOKIE_SAME_SITE_KIND_LAX);
		dualize(RETVAL, "COREWEBVIEW2_COOKIE_SAME_SITE_KIND_LAX");
	OUTPUT:
		RETVAL

SV*
COOKIE_SAME_SITE_KIND_STRICT()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_COOKIE_SAME_SITE_KIND_STRICT);
		dualize(RETVAL, "COREWEBVIEW2_COOKIE_SAME_SITE_KIND_STRICT");
	OUTPUT:
		RETVAL

#
# HOST_RESOURCE_ACCESS_KIND
#

SV*
HOST_RESOURCE_ACCESS_KIND_DENY()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_HOST_RESOURCE_ACCESS_KIND_DENY);
		dualize(RETVAL, "COREWEBVIEW2_HOST_RESOURCE_ACCESS_KIND_DENY");
	OUTPUT:
		RETVAL

SV*
HOST_RESOURCE_ACCESS_KIND_ALLOW()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_HOST_RESOURCE_ACCESS_KIND_ALLOW);
		dualize(RETVAL, "COREWEBVIEW2_HOST_RESOURCE_ACCESS_KIND_ALLOW");
	OUTPUT:
		RETVAL

SV*
HOST_RESOURCE_ACCESS_KIND_DENY_CORS()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_HOST_RESOURCE_ACCESS_KIND_DENY_CORS);
		dualize(RETVAL, "COREWEBVIEW2_HOST_RESOURCE_ACCESS_KIND_DENY_CORS");
	OUTPUT:
		RETVAL

#
# SCRIPT_DIALOG_KIND
#

SV*
SCRIPT_DIALOG_KIND_ALERT()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_SCRIPT_DIALOG_KIND_ALERT);
		dualize(RETVAL, "COREWEBVIEW2_SCRIPT_DIALOG_KIND_ALERT");
	OUTPUT:
		RETVAL

SV*
SCRIPT_DIALOG_KIND_CONFIRM()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_SCRIPT_DIALOG_KIND_CONFIRM);
		dualize(RETVAL, "COREWEBVIEW2_SCRIPT_DIALOG_KIND_CONFIRM");
	OUTPUT:
		RETVAL

SV*
SCRIPT_DIALOG_KIND_PROMPT()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_SCRIPT_DIALOG_KIND_PROMPT);
		dualize(RETVAL, "COREWEBVIEW2_SCRIPT_DIALOG_KIND_PROMPT");
	OUTPUT:
		RETVAL

SV*
SCRIPT_DIALOG_KIND_BEFOREUNLOAD()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_SCRIPT_DIALOG_KIND_BEFOREUNLOAD);
		dualize(RETVAL, "COREWEBVIEW2_SCRIPT_DIALOG_KIND_BEFOREUNLOAD");
	OUTPUT:
		RETVAL

#
# PROCESS_FAILED_KIND
#

SV*
PROCESS_FAILED_KIND_BROWSER_PROCESS_EXITED()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_PROCESS_FAILED_KIND_BROWSER_PROCESS_EXITED);
		dualize(RETVAL, "COREWEBVIEW2_PROCESS_FAILED_KIND_BROWSER_PROCESS_EXITED");
	OUTPUT:
		RETVAL

SV*
PROCESS_FAILED_KIND_RENDER_PROCESS_EXITED()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_PROCESS_FAILED_KIND_RENDER_PROCESS_EXITED);
		dualize(RETVAL, "COREWEBVIEW2_PROCESS_FAILED_KIND_RENDER_PROCESS_EXITED");
	OUTPUT:
		RETVAL

SV*
PROCESS_FAILED_KIND_RENDER_PROCESS_UNRESPONSIVE()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_PROCESS_FAILED_KIND_RENDER_PROCESS_UNRESPONSIVE);
		dualize(RETVAL, "COREWEBVIEW2_PROCESS_FAILED_KIND_RENDER_PROCESS_UNRESPONSIVE");
	OUTPUT:
		RETVAL

SV*
PROCESS_FAILED_KIND_FRAME_RENDER_PROCESS_EXITED()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_PROCESS_FAILED_KIND_FRAME_RENDER_PROCESS_EXITED);
		dualize(RETVAL, "COREWEBVIEW2_PROCESS_FAILED_KIND_FRAME_RENDER_PROCESS_EXITED");
	OUTPUT:
		RETVAL

SV*
PROCESS_FAILED_KIND_UTILITY_PROCESS_EXITED()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_PROCESS_FAILED_KIND_UTILITY_PROCESS_EXITED);
		dualize(RETVAL, "COREWEBVIEW2_PROCESS_FAILED_KIND_UTILITY_PROCESS_EXITED");
	OUTPUT:
		RETVAL

SV*
PROCESS_FAILED_KIND_SANDBOX_HELPER_PROCESS_EXITED()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_PROCESS_FAILED_KIND_SANDBOX_HELPER_PROCESS_EXITED);
		dualize(RETVAL, "COREWEBVIEW2_PROCESS_FAILED_KIND_SANDBOX_HELPER_PROCESS_EXITED");
	OUTPUT:
		RETVAL

SV*
PROCESS_FAILED_KIND_GPU_PROCESS_EXITED()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_PROCESS_FAILED_KIND_GPU_PROCESS_EXITED);
		dualize(RETVAL, "COREWEBVIEW2_PROCESS_FAILED_KIND_GPU_PROCESS_EXITED");
	OUTPUT:
		RETVAL

SV*
PROCESS_FAILED_KIND_PPAPI_PLUGIN_PROCESS_EXITED()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_PROCESS_FAILED_KIND_PPAPI_PLUGIN_PROCESS_EXITED);
		dualize(RETVAL, "COREWEBVIEW2_PROCESS_FAILED_KIND_PPAPI_PLUGIN_PROCESS_EXITED");
	OUTPUT:
		RETVAL

SV*
PROCESS_FAILED_KIND_PPAPI_BROKER_PROCESS_EXITED()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_PROCESS_FAILED_KIND_PPAPI_BROKER_PROCESS_EXITED);
		dualize(RETVAL, "COREWEBVIEW2_PROCESS_FAILED_KIND_PPAPI_BROKER_PROCESS_EXITED");
	OUTPUT:
		RETVAL

SV*
PROCESS_FAILED_KIND_UNKNOWN_PROCESS_EXITED()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_PROCESS_FAILED_KIND_UNKNOWN_PROCESS_EXITED);
		dualize(RETVAL, "COREWEBVIEW2_PROCESS_FAILED_KIND_UNKNOWN_PROCESS_EXITED");
	OUTPUT:
		RETVAL

#
# PROCESS_FAILED_REASON
#

SV*
PROCESS_FAILED_REASON_UNEXPECTED()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_PROCESS_FAILED_REASON_UNEXPECTED);
		dualize(RETVAL, "COREWEBVIEW2_PROCESS_FAILED_REASON_UNEXPECTED");
	OUTPUT:
		RETVAL

SV*
PROCESS_FAILED_REASON_UNRESPONSIVE()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_PROCESS_FAILED_REASON_UNRESPONSIVE);
		dualize(RETVAL, "COREWEBVIEW2_PROCESS_FAILED_REASON_UNRESPONSIVE");
	OUTPUT:
		RETVAL

SV*
PROCESS_FAILED_REASON_TERMINATED()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_PROCESS_FAILED_REASON_TERMINATED);
		dualize(RETVAL, "COREWEBVIEW2_PROCESS_FAILED_REASON_TERMINATED");
	OUTPUT:
		RETVAL

SV*
PROCESS_FAILED_REASON_CRASHED()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_PROCESS_FAILED_REASON_CRASHED);
		dualize(RETVAL, "COREWEBVIEW2_PROCESS_FAILED_REASON_CRASHED");
	OUTPUT:
		RETVAL

SV*
PROCESS_FAILED_REASON_LAUNCH_FAILED()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_PROCESS_FAILED_REASON_LAUNCH_FAILED);
		dualize(RETVAL, "COREWEBVIEW2_PROCESS_FAILED_REASON_LAUNCH_FAILED");
	OUTPUT:
		RETVAL

SV*
PROCESS_FAILED_REASON_OUT_OF_MEMORY()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_PROCESS_FAILED_REASON_OUT_OF_MEMORY);
		dualize(RETVAL, "COREWEBVIEW2_PROCESS_FAILED_REASON_OUT_OF_MEMORY");
	OUTPUT:
		RETVAL

SV*
PROCESS_FAILED_REASON_PROFILE_DELETED()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_PROCESS_FAILED_REASON_PROFILE_DELETED);
		dualize(RETVAL, "COREWEBVIEW2_PROCESS_FAILED_REASON_PROFILE_DELETED");
	OUTPUT:
		RETVAL

#
# PERMISSION_KIND
#

SV*
PERMISSION_KIND_UNKNOWN_PERMISSION()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_PERMISSION_KIND_UNKNOWN_PERMISSION);
		dualize(RETVAL, "COREWEBVIEW2_PERMISSION_KIND_UNKNOWN_PERMISSION");
	OUTPUT:
		RETVAL

SV*
PERMISSION_KIND_MICROPHONE()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_PERMISSION_KIND_MICROPHONE);
		dualize(RETVAL, "COREWEBVIEW2_PERMISSION_KIND_MICROPHONE");
	OUTPUT:
		RETVAL

SV*
PERMISSION_KIND_CAMERA()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_PERMISSION_KIND_CAMERA);
		dualize(RETVAL, "COREWEBVIEW2_PERMISSION_KIND_CAMERA");
	OUTPUT:
		RETVAL

SV*
PERMISSION_KIND_GEOLOCATION()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_PERMISSION_KIND_GEOLOCATION);
		dualize(RETVAL, "COREWEBVIEW2_PERMISSION_KIND_GEOLOCATION");
	OUTPUT:
		RETVAL

SV*
PERMISSION_KIND_NOTIFICATIONS()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_PERMISSION_KIND_NOTIFICATIONS);
		dualize(RETVAL, "COREWEBVIEW2_PERMISSION_KIND_NOTIFICATIONS");
	OUTPUT:
		RETVAL

SV*
PERMISSION_KIND_OTHER_SENSORS()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_PERMISSION_KIND_OTHER_SENSORS);
		dualize(RETVAL, "COREWEBVIEW2_PERMISSION_KIND_OTHER_SENSORS");
	OUTPUT:
		RETVAL

SV*
PERMISSION_KIND_CLIPBOARD_READ()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_PERMISSION_KIND_CLIPBOARD_READ);
		dualize(RETVAL, "COREWEBVIEW2_PERMISSION_KIND_CLIPBOARD_READ");
	OUTPUT:
		RETVAL

SV*
PERMISSION_KIND_MULTIPLE_AUTOMATIC_DOWNLOADS()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_PERMISSION_KIND_MULTIPLE_AUTOMATIC_DOWNLOADS);
		dualize(RETVAL, "COREWEBVIEW2_PERMISSION_KIND_MULTIPLE_AUTOMATIC_DOWNLOADS");
	OUTPUT:
		RETVAL

SV*
PERMISSION_KIND_FILE_READ_WRITE()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_PERMISSION_KIND_FILE_READ_WRITE);
		dualize(RETVAL, "COREWEBVIEW2_PERMISSION_KIND_FILE_READ_WRITE");
	OUTPUT:
		RETVAL

SV*
PERMISSION_KIND_AUTOPLAY()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_PERMISSION_KIND_AUTOPLAY);
		dualize(RETVAL, "COREWEBVIEW2_PERMISSION_KIND_AUTOPLAY");
	OUTPUT:
		RETVAL

SV*
PERMISSION_KIND_LOCAL_FONTS()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_PERMISSION_KIND_LOCAL_FONTS);
		dualize(RETVAL, "COREWEBVIEW2_PERMISSION_KIND_LOCAL_FONTS");
	OUTPUT:
		RETVAL

SV*
PERMISSION_KIND_MIDI_SYSTEM_EXCLUSIVE_MESSAGES()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_PERMISSION_KIND_MIDI_SYSTEM_EXCLUSIVE_MESSAGES);
		dualize(RETVAL, "COREWEBVIEW2_PERMISSION_KIND_MIDI_SYSTEM_EXCLUSIVE_MESSAGES");
	OUTPUT:
		RETVAL

SV*
PERMISSION_KIND_WINDOW_MANAGEMENT()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_PERMISSION_KIND_WINDOW_MANAGEMENT);
		dualize(RETVAL, "COREWEBVIEW2_PERMISSION_KIND_WINDOW_MANAGEMENT");
	OUTPUT:
		RETVAL

#
# PERMISSION_STATE
#

SV*
PERMISSION_STATE_DEFAULT()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_PERMISSION_STATE_DEFAULT);
		dualize(RETVAL, "COREWEBVIEW2_PERMISSION_STATE_DEFAULT");
	OUTPUT:
		RETVAL

SV*
PERMISSION_STATE_ALLOW()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_PERMISSION_STATE_ALLOW);
		dualize(RETVAL, "COREWEBVIEW2_PERMISSION_STATE_ALLOW");
	OUTPUT:
		RETVAL

SV*
PERMISSION_STATE_DENY()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_PERMISSION_STATE_DENY);
		dualize(RETVAL, "COREWEBVIEW2_PERMISSION_STATE_DENY");
	OUTPUT:
		RETVAL

#
# WEB_ERROR_STATUS
#

SV*
WEB_ERROR_STATUS_UNKNOWN()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_WEB_ERROR_STATUS_UNKNOWN);
		dualize(RETVAL, "COREWEBVIEW2_WEB_ERROR_STATUS_UNKNOWN");
	OUTPUT:
		RETVAL

SV*
WEB_ERROR_STATUS_CERTIFICATE_COMMON_NAME_IS_INCORRECT()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_WEB_ERROR_STATUS_CERTIFICATE_COMMON_NAME_IS_INCORRECT);
		dualize(RETVAL, "COREWEBVIEW2_WEB_ERROR_STATUS_CERTIFICATE_COMMON_NAME_IS_INCORRECT");
	OUTPUT:
		RETVAL

SV*
WEB_ERROR_STATUS_CERTIFICATE_EXPIRED()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_WEB_ERROR_STATUS_CERTIFICATE_EXPIRED);
		dualize(RETVAL, "COREWEBVIEW2_WEB_ERROR_STATUS_CERTIFICATE_EXPIRED");
	OUTPUT:
		RETVAL

SV*
WEB_ERROR_STATUS_CLIENT_CERTIFICATE_CONTAINS_ERRORS()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_WEB_ERROR_STATUS_CLIENT_CERTIFICATE_CONTAINS_ERRORS);
		dualize(RETVAL, "COREWEBVIEW2_WEB_ERROR_STATUS_CLIENT_CERTIFICATE_CONTAINS_ERRORS");
	OUTPUT:
		RETVAL

SV*
WEB_ERROR_STATUS_CERTIFICATE_REVOKED()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_WEB_ERROR_STATUS_CERTIFICATE_REVOKED);
		dualize(RETVAL, "COREWEBVIEW2_WEB_ERROR_STATUS_CERTIFICATE_REVOKED");
	OUTPUT:
		RETVAL

SV*
WEB_ERROR_STATUS_CERTIFICATE_IS_INVALID()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_WEB_ERROR_STATUS_CERTIFICATE_IS_INVALID);
		dualize(RETVAL, "COREWEBVIEW2_WEB_ERROR_STATUS_CERTIFICATE_IS_INVALID");
	OUTPUT:
		RETVAL

SV*
WEB_ERROR_STATUS_SERVER_UNREACHABLE()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_WEB_ERROR_STATUS_SERVER_UNREACHABLE);
		dualize(RETVAL, "COREWEBVIEW2_WEB_ERROR_STATUS_SERVER_UNREACHABLE");
	OUTPUT:
		RETVAL

SV*
WEB_ERROR_STATUS_TIMEOUT()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_WEB_ERROR_STATUS_TIMEOUT);
		dualize(RETVAL, "COREWEBVIEW2_WEB_ERROR_STATUS_TIMEOUT");
	OUTPUT:
		RETVAL

SV*
WEB_ERROR_STATUS_ERROR_HTTP_INVALID_SERVER_RESPONSE()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_WEB_ERROR_STATUS_ERROR_HTTP_INVALID_SERVER_RESPONSE);
		dualize(RETVAL, "COREWEBVIEW2_WEB_ERROR_STATUS_ERROR_HTTP_INVALID_SERVER_RESPONSE");
	OUTPUT:
		RETVAL

SV*
WEB_ERROR_STATUS_CONNECTION_ABORTED()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_WEB_ERROR_STATUS_CONNECTION_ABORTED);
		dualize(RETVAL, "COREWEBVIEW2_WEB_ERROR_STATUS_CONNECTION_ABORTED");
	OUTPUT:
		RETVAL

SV*
WEB_ERROR_STATUS_CONNECTION_RESET()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_WEB_ERROR_STATUS_CONNECTION_RESET);
		dualize(RETVAL, "COREWEBVIEW2_WEB_ERROR_STATUS_CONNECTION_RESET");
	OUTPUT:
		RETVAL

SV*
WEB_ERROR_STATUS_DISCONNECTED()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_WEB_ERROR_STATUS_DISCONNECTED);
		dualize(RETVAL, "COREWEBVIEW2_WEB_ERROR_STATUS_DISCONNECTED");
	OUTPUT:
		RETVAL

SV*
WEB_ERROR_STATUS_CANNOT_CONNECT()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_WEB_ERROR_STATUS_CANNOT_CONNECT);
		dualize(RETVAL, "COREWEBVIEW2_WEB_ERROR_STATUS_CANNOT_CONNECT");
	OUTPUT:
		RETVAL

SV*
WEB_ERROR_STATUS_HOST_NAME_NOT_RESOLVED()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_WEB_ERROR_STATUS_HOST_NAME_NOT_RESOLVED);
		dualize(RETVAL, "COREWEBVIEW2_WEB_ERROR_STATUS_HOST_NAME_NOT_RESOLVED");
	OUTPUT:
		RETVAL

SV*
WEB_ERROR_STATUS_OPERATION_CANCELED()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_WEB_ERROR_STATUS_OPERATION_CANCELED);
		dualize(RETVAL, "COREWEBVIEW2_WEB_ERROR_STATUS_OPERATION_CANCELED");
	OUTPUT:
		RETVAL

SV*
WEB_ERROR_STATUS_REDIRECT_FAILED()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_WEB_ERROR_STATUS_REDIRECT_FAILED);
		dualize(RETVAL, "COREWEBVIEW2_WEB_ERROR_STATUS_REDIRECT_FAILED");
	OUTPUT:
		RETVAL

SV*
WEB_ERROR_STATUS_UNEXPECTED_ERROR()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_WEB_ERROR_STATUS_UNEXPECTED_ERROR);
		dualize(RETVAL, "COREWEBVIEW2_WEB_ERROR_STATUS_UNEXPECTED_ERROR");
	OUTPUT:
		RETVAL

SV*
WEB_ERROR_STATUS_VALID_AUTHENTICATION_CREDENTIALS_REQUIRED()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_WEB_ERROR_STATUS_VALID_AUTHENTICATION_CREDENTIALS_REQUIRED);
		dualize(RETVAL, "COREWEBVIEW2_WEB_ERROR_STATUS_VALID_AUTHENTICATION_CREDENTIALS_REQUIRED");
	OUTPUT:
		RETVAL

SV*
WEB_ERROR_STATUS_VALID_PROXY_AUTHENTICATION_REQUIRED()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_WEB_ERROR_STATUS_VALID_PROXY_AUTHENTICATION_REQUIRED);
		dualize(RETVAL, "COREWEBVIEW2_WEB_ERROR_STATUS_VALID_PROXY_AUTHENTICATION_REQUIRED");
	OUTPUT:
		RETVAL

#
# WEB_RESOURCE_CONTEXT
#

SV*
WEB_RESOURCE_CONTEXT_ALL()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_WEB_RESOURCE_CONTEXT_ALL);
		dualize(RETVAL, "COREWEBVIEW2_WEB_RESOURCE_CONTEXT_ALL");
	OUTPUT:
		RETVAL

SV*
WEB_RESOURCE_CONTEXT_DOCUMENT()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_WEB_RESOURCE_CONTEXT_DOCUMENT);
		dualize(RETVAL, "COREWEBVIEW2_WEB_RESOURCE_CONTEXT_DOCUMENT");
	OUTPUT:
		RETVAL

SV*
WEB_RESOURCE_CONTEXT_STYLESHEET()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_WEB_RESOURCE_CONTEXT_STYLESHEET);
		dualize(RETVAL, "COREWEBVIEW2_WEB_RESOURCE_CONTEXT_STYLESHEET");
	OUTPUT:
		RETVAL

SV*
WEB_RESOURCE_CONTEXT_IMAGE()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_WEB_RESOURCE_CONTEXT_IMAGE);
		dualize(RETVAL, "COREWEBVIEW2_WEB_RESOURCE_CONTEXT_IMAGE");
	OUTPUT:
		RETVAL

SV*
WEB_RESOURCE_CONTEXT_MEDIA()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_WEB_RESOURCE_CONTEXT_MEDIA);
		dualize(RETVAL, "COREWEBVIEW2_WEB_RESOURCE_CONTEXT_MEDIA");
	OUTPUT:
		RETVAL

SV*
WEB_RESOURCE_CONTEXT_FONT()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_WEB_RESOURCE_CONTEXT_FONT);
		dualize(RETVAL, "COREWEBVIEW2_WEB_RESOURCE_CONTEXT_FONT");
	OUTPUT:
		RETVAL

SV*
WEB_RESOURCE_CONTEXT_SCRIPT()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_WEB_RESOURCE_CONTEXT_SCRIPT);
		dualize(RETVAL, "COREWEBVIEW2_WEB_RESOURCE_CONTEXT_SCRIPT");
	OUTPUT:
		RETVAL

SV*
WEB_RESOURCE_CONTEXT_XML_HTTP_REQUEST()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_WEB_RESOURCE_CONTEXT_XML_HTTP_REQUEST);
		dualize(RETVAL, "COREWEBVIEW2_WEB_RESOURCE_CONTEXT_XML_HTTP_REQUEST");
	OUTPUT:
		RETVAL

SV*
WEB_RESOURCE_CONTEXT_FETCH()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_WEB_RESOURCE_CONTEXT_FETCH);
		dualize(RETVAL, "COREWEBVIEW2_WEB_RESOURCE_CONTEXT_FETCH");
	OUTPUT:
		RETVAL

SV*
WEB_RESOURCE_CONTEXT_TEXT_TRACK()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_WEB_RESOURCE_CONTEXT_TEXT_TRACK);
		dualize(RETVAL, "COREWEBVIEW2_WEB_RESOURCE_CONTEXT_TEXT_TRACK");
	OUTPUT:
		RETVAL

SV*
WEB_RESOURCE_CONTEXT_EVENT_SOURCE()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_WEB_RESOURCE_CONTEXT_EVENT_SOURCE);
		dualize(RETVAL, "COREWEBVIEW2_WEB_RESOURCE_CONTEXT_EVENT_SOURCE");
	OUTPUT:
		RETVAL

SV*
WEB_RESOURCE_CONTEXT_WEBSOCKET()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_WEB_RESOURCE_CONTEXT_WEBSOCKET);
		dualize(RETVAL, "COREWEBVIEW2_WEB_RESOURCE_CONTEXT_WEBSOCKET");
	OUTPUT:
		RETVAL

SV*
WEB_RESOURCE_CONTEXT_MANIFEST()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_WEB_RESOURCE_CONTEXT_MANIFEST);
		dualize(RETVAL, "COREWEBVIEW2_WEB_RESOURCE_CONTEXT_MANIFEST");
	OUTPUT:
		RETVAL

SV*
WEB_RESOURCE_CONTEXT_SIGNED_EXCHANGE()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_WEB_RESOURCE_CONTEXT_SIGNED_EXCHANGE);
		dualize(RETVAL, "COREWEBVIEW2_WEB_RESOURCE_CONTEXT_SIGNED_EXCHANGE");
	OUTPUT:
		RETVAL

SV*
WEB_RESOURCE_CONTEXT_PING()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_WEB_RESOURCE_CONTEXT_PING);
		dualize(RETVAL, "COREWEBVIEW2_WEB_RESOURCE_CONTEXT_PING");
	OUTPUT:
		RETVAL

SV*
WEB_RESOURCE_CONTEXT_CSP_VIOLATION_REPORT()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_WEB_RESOURCE_CONTEXT_CSP_VIOLATION_REPORT);
		dualize(RETVAL, "COREWEBVIEW2_WEB_RESOURCE_CONTEXT_CSP_VIOLATION_REPORT");
	OUTPUT:
		RETVAL

SV*
WEB_RESOURCE_CONTEXT_OTHER()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_WEB_RESOURCE_CONTEXT_OTHER);
		dualize(RETVAL, "COREWEBVIEW2_WEB_RESOURCE_CONTEXT_OTHER");
	OUTPUT:
		RETVAL

#
# MOVE_FOCUS_REASON
#

SV*
MOVE_FOCUS_REASON_PROGRAMMATIC()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_MOVE_FOCUS_REASON_PROGRAMMATIC);
		dualize(RETVAL, "COREWEBVIEW2_MOVE_FOCUS_REASON_PROGRAMMATIC");
	OUTPUT:
		RETVAL

SV*
MOVE_FOCUS_REASON_NEXT()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_MOVE_FOCUS_REASON_NEXT);
		dualize(RETVAL, "COREWEBVIEW2_MOVE_FOCUS_REASON_NEXT");
	OUTPUT:
		RETVAL

SV*
MOVE_FOCUS_REASON_PREVIOUS()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_MOVE_FOCUS_REASON_PREVIOUS);
		dualize(RETVAL, "COREWEBVIEW2_MOVE_FOCUS_REASON_PREVIOUS");
	OUTPUT:
		RETVAL

#
# KEY_EVENT_KIND
#

SV*
KEY_EVENT_KIND_KEY_DOWN()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_KEY_EVENT_KIND_KEY_DOWN);
		dualize(RETVAL, "COREWEBVIEW2_KEY_EVENT_KIND_KEY_DOWN");
	OUTPUT:
		RETVAL

SV*
KEY_EVENT_KIND_KEY_UP()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_KEY_EVENT_KIND_KEY_UP);
		dualize(RETVAL, "COREWEBVIEW2_KEY_EVENT_KIND_KEY_UP");
	OUTPUT:
		RETVAL

SV*
KEY_EVENT_KIND_SYSTEM_KEY_DOWN()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_KEY_EVENT_KIND_SYSTEM_KEY_DOWN);
		dualize(RETVAL, "COREWEBVIEW2_KEY_EVENT_KIND_SYSTEM_KEY_DOWN");
	OUTPUT:
		RETVAL

SV*
KEY_EVENT_KIND_SYSTEM_KEY_UP()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_KEY_EVENT_KIND_SYSTEM_KEY_UP);
		dualize(RETVAL, "COREWEBVIEW2_KEY_EVENT_KIND_SYSTEM_KEY_UP");
	OUTPUT:
		RETVAL

#
# BROWSER_PROCESS_EXIT_KIND
#

SV*
BROWSER_PROCESS_EXIT_KIND_NORMAL()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_BROWSER_PROCESS_EXIT_KIND_NORMAL);
		dualize(RETVAL, "COREWEBVIEW2_BROWSER_PROCESS_EXIT_KIND_NORMAL");
	OUTPUT:
		RETVAL

SV*
BROWSER_PROCESS_EXIT_KIND_FAILED()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_BROWSER_PROCESS_EXIT_KIND_FAILED);
		dualize(RETVAL, "COREWEBVIEW2_BROWSER_PROCESS_EXIT_KIND_FAILED");
	OUTPUT:
		RETVAL

#
# MOUSE_EVENT_KIND
#

SV*
MOUSE_EVENT_KIND_HORIZONTAL_WHEEL()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_MOUSE_EVENT_KIND_HORIZONTAL_WHEEL);
		dualize(RETVAL, "COREWEBVIEW2_MOUSE_EVENT_KIND_HORIZONTAL_WHEEL");
	OUTPUT:
		RETVAL

SV*
MOUSE_EVENT_KIND_LEFT_BUTTON_DOUBLE_CLICK()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_MOUSE_EVENT_KIND_LEFT_BUTTON_DOUBLE_CLICK);
		dualize(RETVAL, "COREWEBVIEW2_MOUSE_EVENT_KIND_LEFT_BUTTON_DOUBLE_CLICK");
	OUTPUT:
		RETVAL

SV*
MOUSE_EVENT_KIND_LEFT_BUTTON_DOWN()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_MOUSE_EVENT_KIND_LEFT_BUTTON_DOWN);
		dualize(RETVAL, "COREWEBVIEW2_MOUSE_EVENT_KIND_LEFT_BUTTON_DOWN");
	OUTPUT:
		RETVAL

SV*
MOUSE_EVENT_KIND_LEFT_BUTTON_UP()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_MOUSE_EVENT_KIND_LEFT_BUTTON_UP);
		dualize(RETVAL, "COREWEBVIEW2_MOUSE_EVENT_KIND_LEFT_BUTTON_UP");
	OUTPUT:
		RETVAL

SV*
MOUSE_EVENT_KIND_LEAVE()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_MOUSE_EVENT_KIND_LEAVE);
		dualize(RETVAL, "COREWEBVIEW2_MOUSE_EVENT_KIND_LEAVE");
	OUTPUT:
		RETVAL

SV*
MOUSE_EVENT_KIND_MIDDLE_BUTTON_DOUBLE_CLICK()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_MOUSE_EVENT_KIND_MIDDLE_BUTTON_DOUBLE_CLICK);
		dualize(RETVAL, "COREWEBVIEW2_MOUSE_EVENT_KIND_MIDDLE_BUTTON_DOUBLE_CLICK");
	OUTPUT:
		RETVAL

SV*
MOUSE_EVENT_KIND_MIDDLE_BUTTON_DOWN()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_MOUSE_EVENT_KIND_MIDDLE_BUTTON_DOWN);
		dualize(RETVAL, "COREWEBVIEW2_MOUSE_EVENT_KIND_MIDDLE_BUTTON_DOWN");
	OUTPUT:
		RETVAL

SV*
MOUSE_EVENT_KIND_MIDDLE_BUTTON_UP()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_MOUSE_EVENT_KIND_MIDDLE_BUTTON_UP);
		dualize(RETVAL, "COREWEBVIEW2_MOUSE_EVENT_KIND_MIDDLE_BUTTON_UP");
	OUTPUT:
		RETVAL

SV*
MOUSE_EVENT_KIND_MOVE()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_MOUSE_EVENT_KIND_MOVE);
		dualize(RETVAL, "COREWEBVIEW2_MOUSE_EVENT_KIND_MOVE");
	OUTPUT:
		RETVAL

SV*
MOUSE_EVENT_KIND_RIGHT_BUTTON_DOUBLE_CLICK()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_MOUSE_EVENT_KIND_RIGHT_BUTTON_DOUBLE_CLICK);
		dualize(RETVAL, "COREWEBVIEW2_MOUSE_EVENT_KIND_RIGHT_BUTTON_DOUBLE_CLICK");
	OUTPUT:
		RETVAL

SV*
MOUSE_EVENT_KIND_RIGHT_BUTTON_DOWN()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_MOUSE_EVENT_KIND_RIGHT_BUTTON_DOWN);
		dualize(RETVAL, "COREWEBVIEW2_MOUSE_EVENT_KIND_RIGHT_BUTTON_DOWN");
	OUTPUT:
		RETVAL

SV*
MOUSE_EVENT_KIND_RIGHT_BUTTON_UP()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_MOUSE_EVENT_KIND_RIGHT_BUTTON_UP);
		dualize(RETVAL, "COREWEBVIEW2_MOUSE_EVENT_KIND_RIGHT_BUTTON_UP");
	OUTPUT:
		RETVAL

SV*
MOUSE_EVENT_KIND_WHEEL()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_MOUSE_EVENT_KIND_WHEEL);
		dualize(RETVAL, "COREWEBVIEW2_MOUSE_EVENT_KIND_WHEEL");
	OUTPUT:
		RETVAL

SV*
MOUSE_EVENT_KIND_X_BUTTON_DOUBLE_CLICK()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_MOUSE_EVENT_KIND_X_BUTTON_DOUBLE_CLICK);
		dualize(RETVAL, "COREWEBVIEW2_MOUSE_EVENT_KIND_X_BUTTON_DOUBLE_CLICK");
	OUTPUT:
		RETVAL

SV*
MOUSE_EVENT_KIND_X_BUTTON_DOWN()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_MOUSE_EVENT_KIND_X_BUTTON_DOWN);
		dualize(RETVAL, "COREWEBVIEW2_MOUSE_EVENT_KIND_X_BUTTON_DOWN");
	OUTPUT:
		RETVAL

SV*
MOUSE_EVENT_KIND_X_BUTTON_UP()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_MOUSE_EVENT_KIND_X_BUTTON_UP);
		dualize(RETVAL, "COREWEBVIEW2_MOUSE_EVENT_KIND_X_BUTTON_UP");
	OUTPUT:
		RETVAL

SV*
MOUSE_EVENT_KIND_NON_CLIENT_RIGHT_BUTTON_DOWN()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_MOUSE_EVENT_KIND_NON_CLIENT_RIGHT_BUTTON_DOWN);
		dualize(RETVAL, "COREWEBVIEW2_MOUSE_EVENT_KIND_NON_CLIENT_RIGHT_BUTTON_DOWN");
	OUTPUT:
		RETVAL

SV*
MOUSE_EVENT_KIND_NON_CLIENT_RIGHT_BUTTON_UP()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_MOUSE_EVENT_KIND_NON_CLIENT_RIGHT_BUTTON_UP);
		dualize(RETVAL, "COREWEBVIEW2_MOUSE_EVENT_KIND_NON_CLIENT_RIGHT_BUTTON_UP");
	OUTPUT:
		RETVAL

#
# MOUSE_EVENT_VIRTUAL_KEYS
#

SV*
MOUSE_EVENT_VIRTUAL_KEYS_NONE()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_MOUSE_EVENT_VIRTUAL_KEYS_NONE);
		dualize(RETVAL, "COREWEBVIEW2_MOUSE_EVENT_VIRTUAL_KEYS_NONE");
	OUTPUT:
		RETVAL

SV*
MOUSE_EVENT_VIRTUAL_KEYS_LEFT_BUTTON()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_MOUSE_EVENT_VIRTUAL_KEYS_LEFT_BUTTON);
		dualize(RETVAL, "COREWEBVIEW2_MOUSE_EVENT_VIRTUAL_KEYS_LEFT_BUTTON");
	OUTPUT:
		RETVAL

SV*
MOUSE_EVENT_VIRTUAL_KEYS_RIGHT_BUTTON()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_MOUSE_EVENT_VIRTUAL_KEYS_RIGHT_BUTTON);
		dualize(RETVAL, "COREWEBVIEW2_MOUSE_EVENT_VIRTUAL_KEYS_RIGHT_BUTTON");
	OUTPUT:
		RETVAL

SV*
MOUSE_EVENT_VIRTUAL_KEYS_SHIFT()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_MOUSE_EVENT_VIRTUAL_KEYS_SHIFT);
		dualize(RETVAL, "COREWEBVIEW2_MOUSE_EVENT_VIRTUAL_KEYS_SHIFT");
	OUTPUT:
		RETVAL

SV*
MOUSE_EVENT_VIRTUAL_KEYS_CONTROL()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_MOUSE_EVENT_VIRTUAL_KEYS_CONTROL);
		dualize(RETVAL, "COREWEBVIEW2_MOUSE_EVENT_VIRTUAL_KEYS_CONTROL");
	OUTPUT:
		RETVAL

SV*
MOUSE_EVENT_VIRTUAL_KEYS_MIDDLE_BUTTON()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_MOUSE_EVENT_VIRTUAL_KEYS_MIDDLE_BUTTON);
		dualize(RETVAL, "COREWEBVIEW2_MOUSE_EVENT_VIRTUAL_KEYS_MIDDLE_BUTTON");
	OUTPUT:
		RETVAL

SV*
MOUSE_EVENT_VIRTUAL_KEYS_X_BUTTON1()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_MOUSE_EVENT_VIRTUAL_KEYS_X_BUTTON1);
		dualize(RETVAL, "COREWEBVIEW2_MOUSE_EVENT_VIRTUAL_KEYS_X_BUTTON1");
	OUTPUT:
		RETVAL

SV*
MOUSE_EVENT_VIRTUAL_KEYS_X_BUTTON2()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_MOUSE_EVENT_VIRTUAL_KEYS_X_BUTTON2);
		dualize(RETVAL, "COREWEBVIEW2_MOUSE_EVENT_VIRTUAL_KEYS_X_BUTTON2");
	OUTPUT:
		RETVAL

#
# POINTER_EVENT_KIND
#

SV*
POINTER_EVENT_KIND_ACTIVATE()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_POINTER_EVENT_KIND_ACTIVATE);
		dualize(RETVAL, "COREWEBVIEW2_POINTER_EVENT_KIND_ACTIVATE");
	OUTPUT:
		RETVAL

SV*
POINTER_EVENT_KIND_DOWN()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_POINTER_EVENT_KIND_DOWN);
		dualize(RETVAL, "COREWEBVIEW2_POINTER_EVENT_KIND_DOWN");
	OUTPUT:
		RETVAL

SV*
POINTER_EVENT_KIND_ENTER()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_POINTER_EVENT_KIND_ENTER);
		dualize(RETVAL, "COREWEBVIEW2_POINTER_EVENT_KIND_ENTER");
	OUTPUT:
		RETVAL

SV*
POINTER_EVENT_KIND_LEAVE()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_POINTER_EVENT_KIND_LEAVE);
		dualize(RETVAL, "COREWEBVIEW2_POINTER_EVENT_KIND_LEAVE");
	OUTPUT:
		RETVAL

SV*
POINTER_EVENT_KIND_UP()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_POINTER_EVENT_KIND_UP);
		dualize(RETVAL, "COREWEBVIEW2_POINTER_EVENT_KIND_UP");
	OUTPUT:
		RETVAL

SV*
POINTER_EVENT_KIND_UPDATE()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_POINTER_EVENT_KIND_UPDATE);
		dualize(RETVAL, "COREWEBVIEW2_POINTER_EVENT_KIND_UPDATE");
	OUTPUT:
		RETVAL

#
# BOUNDS_MODE
#

SV*
BOUNDS_MODE_USE_RAW_PIXELS()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_BOUNDS_MODE_USE_RAW_PIXELS);
		dualize(RETVAL, "COREWEBVIEW2_BOUNDS_MODE_USE_RAW_PIXELS");
	OUTPUT:
		RETVAL

SV*
BOUNDS_MODE_USE_RASTERIZATION_SCALE()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_BOUNDS_MODE_USE_RASTERIZATION_SCALE);
		dualize(RETVAL, "COREWEBVIEW2_BOUNDS_MODE_USE_RASTERIZATION_SCALE");
	OUTPUT:
		RETVAL

#
# CLIENT_CERTIFICATE_KIND
#

SV*
CLIENT_CERTIFICATE_KIND_SMART_CARD()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_CLIENT_CERTIFICATE_KIND_SMART_CARD);
		dualize(RETVAL, "COREWEBVIEW2_CLIENT_CERTIFICATE_KIND_SMART_CARD");
	OUTPUT:
		RETVAL

SV*
CLIENT_CERTIFICATE_KIND_PIN()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_CLIENT_CERTIFICATE_KIND_PIN);
		dualize(RETVAL, "COREWEBVIEW2_CLIENT_CERTIFICATE_KIND_PIN");
	OUTPUT:
		RETVAL

SV*
CLIENT_CERTIFICATE_KIND_OTHER()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_CLIENT_CERTIFICATE_KIND_OTHER);
		dualize(RETVAL, "COREWEBVIEW2_CLIENT_CERTIFICATE_KIND_OTHER");
	OUTPUT:
		RETVAL

#
# DOWNLOAD_STATE
#

SV*
DOWNLOAD_STATE_IN_PROGRESS()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_DOWNLOAD_STATE_IN_PROGRESS);
		dualize(RETVAL, "COREWEBVIEW2_DOWNLOAD_STATE_IN_PROGRESS");
	OUTPUT:
		RETVAL

SV*
DOWNLOAD_STATE_INTERRUPTED()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_DOWNLOAD_STATE_INTERRUPTED);
		dualize(RETVAL, "COREWEBVIEW2_DOWNLOAD_STATE_INTERRUPTED");
	OUTPUT:
		RETVAL

SV*
DOWNLOAD_STATE_COMPLETED()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_DOWNLOAD_STATE_COMPLETED);
		dualize(RETVAL, "COREWEBVIEW2_DOWNLOAD_STATE_COMPLETED");
	OUTPUT:
		RETVAL

#
# DOWNLOAD_INTERRUPT_REASON
#

SV*
DOWNLOAD_INTERRUPT_REASON_NONE()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_NONE);
		dualize(RETVAL, "COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_NONE");
	OUTPUT:
		RETVAL

SV*
DOWNLOAD_INTERRUPT_REASON_FILE_FAILED()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_FILE_FAILED);
		dualize(RETVAL, "COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_FILE_FAILED");
	OUTPUT:
		RETVAL

SV*
DOWNLOAD_INTERRUPT_REASON_FILE_ACCESS_DENIED()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_FILE_ACCESS_DENIED);
		dualize(RETVAL, "COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_FILE_ACCESS_DENIED");
	OUTPUT:
		RETVAL

SV*
DOWNLOAD_INTERRUPT_REASON_FILE_NO_SPACE()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_FILE_NO_SPACE);
		dualize(RETVAL, "COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_FILE_NO_SPACE");
	OUTPUT:
		RETVAL

SV*
DOWNLOAD_INTERRUPT_REASON_FILE_NAME_TOO_LONG()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_FILE_NAME_TOO_LONG);
		dualize(RETVAL, "COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_FILE_NAME_TOO_LONG");
	OUTPUT:
		RETVAL

SV*
DOWNLOAD_INTERRUPT_REASON_FILE_TOO_LARGE()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_FILE_TOO_LARGE);
		dualize(RETVAL, "COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_FILE_TOO_LARGE");
	OUTPUT:
		RETVAL

SV*
DOWNLOAD_INTERRUPT_REASON_FILE_MALICIOUS()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_FILE_MALICIOUS);
		dualize(RETVAL, "COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_FILE_MALICIOUS");
	OUTPUT:
		RETVAL

SV*
DOWNLOAD_INTERRUPT_REASON_FILE_TRANSIENT_ERROR()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_FILE_TRANSIENT_ERROR);
		dualize(RETVAL, "COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_FILE_TRANSIENT_ERROR");
	OUTPUT:
		RETVAL

SV*
DOWNLOAD_INTERRUPT_REASON_FILE_BLOCKED_BY_POLICY()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_FILE_BLOCKED_BY_POLICY);
		dualize(RETVAL, "COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_FILE_BLOCKED_BY_POLICY");
	OUTPUT:
		RETVAL

SV*
DOWNLOAD_INTERRUPT_REASON_FILE_SECURITY_CHECK_FAILED()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_FILE_SECURITY_CHECK_FAILED);
		dualize(RETVAL, "COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_FILE_SECURITY_CHECK_FAILED");
	OUTPUT:
		RETVAL

SV*
DOWNLOAD_INTERRUPT_REASON_FILE_TOO_SHORT()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_FILE_TOO_SHORT);
		dualize(RETVAL, "COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_FILE_TOO_SHORT");
	OUTPUT:
		RETVAL

SV*
DOWNLOAD_INTERRUPT_REASON_FILE_HASH_MISMATCH()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_FILE_HASH_MISMATCH);
		dualize(RETVAL, "COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_FILE_HASH_MISMATCH");
	OUTPUT:
		RETVAL

SV*
DOWNLOAD_INTERRUPT_REASON_NETWORK_FAILED()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_NETWORK_FAILED);
		dualize(RETVAL, "COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_NETWORK_FAILED");
	OUTPUT:
		RETVAL

SV*
DOWNLOAD_INTERRUPT_REASON_NETWORK_TIMEOUT()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_NETWORK_TIMEOUT);
		dualize(RETVAL, "COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_NETWORK_TIMEOUT");
	OUTPUT:
		RETVAL

SV*
DOWNLOAD_INTERRUPT_REASON_NETWORK_DISCONNECTED()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_NETWORK_DISCONNECTED);
		dualize(RETVAL, "COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_NETWORK_DISCONNECTED");
	OUTPUT:
		RETVAL

SV*
DOWNLOAD_INTERRUPT_REASON_NETWORK_SERVER_DOWN()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_NETWORK_SERVER_DOWN);
		dualize(RETVAL, "COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_NETWORK_SERVER_DOWN");
	OUTPUT:
		RETVAL

SV*
DOWNLOAD_INTERRUPT_REASON_NETWORK_INVALID_REQUEST()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_NETWORK_INVALID_REQUEST);
		dualize(RETVAL, "COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_NETWORK_INVALID_REQUEST");
	OUTPUT:
		RETVAL

SV*
DOWNLOAD_INTERRUPT_REASON_SERVER_FAILED()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_SERVER_FAILED);
		dualize(RETVAL, "COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_SERVER_FAILED");
	OUTPUT:
		RETVAL

SV*
DOWNLOAD_INTERRUPT_REASON_SERVER_NO_RANGE()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_SERVER_NO_RANGE);
		dualize(RETVAL, "COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_SERVER_NO_RANGE");
	OUTPUT:
		RETVAL

SV*
DOWNLOAD_INTERRUPT_REASON_SERVER_BAD_CONTENT()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_SERVER_BAD_CONTENT);
		dualize(RETVAL, "COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_SERVER_BAD_CONTENT");
	OUTPUT:
		RETVAL

SV*
DOWNLOAD_INTERRUPT_REASON_SERVER_UNAUTHORIZED()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_SERVER_UNAUTHORIZED);
		dualize(RETVAL, "COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_SERVER_UNAUTHORIZED");
	OUTPUT:
		RETVAL

SV*
DOWNLOAD_INTERRUPT_REASON_SERVER_CERTIFICATE_PROBLEM()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_SERVER_CERTIFICATE_PROBLEM);
		dualize(RETVAL, "COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_SERVER_CERTIFICATE_PROBLEM");
	OUTPUT:
		RETVAL

SV*
DOWNLOAD_INTERRUPT_REASON_SERVER_FORBIDDEN()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_SERVER_FORBIDDEN);
		dualize(RETVAL, "COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_SERVER_FORBIDDEN");
	OUTPUT:
		RETVAL

SV*
DOWNLOAD_INTERRUPT_REASON_SERVER_UNEXPECTED_RESPONSE()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_SERVER_UNEXPECTED_RESPONSE);
		dualize(RETVAL, "COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_SERVER_UNEXPECTED_RESPONSE");
	OUTPUT:
		RETVAL

SV*
DOWNLOAD_INTERRUPT_REASON_SERVER_CONTENT_LENGTH_MISMATCH()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_SERVER_CONTENT_LENGTH_MISMATCH);
		dualize(RETVAL, "COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_SERVER_CONTENT_LENGTH_MISMATCH");
	OUTPUT:
		RETVAL

SV*
DOWNLOAD_INTERRUPT_REASON_SERVER_CROSS_ORIGIN_REDIRECT()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_SERVER_CROSS_ORIGIN_REDIRECT);
		dualize(RETVAL, "COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_SERVER_CROSS_ORIGIN_REDIRECT");
	OUTPUT:
		RETVAL

SV*
DOWNLOAD_INTERRUPT_REASON_USER_CANCELED()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_USER_CANCELED);
		dualize(RETVAL, "COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_USER_CANCELED");
	OUTPUT:
		RETVAL

SV*
DOWNLOAD_INTERRUPT_REASON_USER_SHUTDOWN()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_USER_SHUTDOWN);
		dualize(RETVAL, "COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_USER_SHUTDOWN");
	OUTPUT:
		RETVAL

SV*
DOWNLOAD_INTERRUPT_REASON_USER_PAUSED()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_USER_PAUSED);
		dualize(RETVAL, "COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_USER_PAUSED");
	OUTPUT:
		RETVAL

SV*
DOWNLOAD_INTERRUPT_REASON_DOWNLOAD_PROCESS_CRASHED()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_DOWNLOAD_PROCESS_CRASHED);
		dualize(RETVAL, "COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_DOWNLOAD_PROCESS_CRASHED");
	OUTPUT:
		RETVAL

#
# PRINT_ORIENTATION
#

SV*
PRINT_ORIENTATION_PORTRAIT()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_PRINT_ORIENTATION_PORTRAIT);
		dualize(RETVAL, "COREWEBVIEW2_PRINT_ORIENTATION_PORTRAIT");
	OUTPUT:
		RETVAL

SV*
PRINT_ORIENTATION_LANDSCAPE()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_PRINT_ORIENTATION_LANDSCAPE);
		dualize(RETVAL, "COREWEBVIEW2_PRINT_ORIENTATION_LANDSCAPE");
	OUTPUT:
		RETVAL

#
# DEFAULT_DOWNLOAD_DIALOG_CORNER_ALIGNMENT
#

SV*
DEFAULT_DOWNLOAD_DIALOG_CORNER_ALIGNMENT_TOP_LEFT()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_DEFAULT_DOWNLOAD_DIALOG_CORNER_ALIGNMENT_TOP_LEFT);
		dualize(RETVAL, "COREWEBVIEW2_DEFAULT_DOWNLOAD_DIALOG_CORNER_ALIGNMENT_TOP_LEFT");
	OUTPUT:
		RETVAL

SV*
DEFAULT_DOWNLOAD_DIALOG_CORNER_ALIGNMENT_TOP_RIGHT()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_DEFAULT_DOWNLOAD_DIALOG_CORNER_ALIGNMENT_TOP_RIGHT);
		dualize(RETVAL, "COREWEBVIEW2_DEFAULT_DOWNLOAD_DIALOG_CORNER_ALIGNMENT_TOP_RIGHT");
	OUTPUT:
		RETVAL

SV*
DEFAULT_DOWNLOAD_DIALOG_CORNER_ALIGNMENT_BOTTOM_LEFT()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_DEFAULT_DOWNLOAD_DIALOG_CORNER_ALIGNMENT_BOTTOM_LEFT);
		dualize(RETVAL, "COREWEBVIEW2_DEFAULT_DOWNLOAD_DIALOG_CORNER_ALIGNMENT_BOTTOM_LEFT");
	OUTPUT:
		RETVAL

SV*
DEFAULT_DOWNLOAD_DIALOG_CORNER_ALIGNMENT_BOTTOM_RIGHT()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_DEFAULT_DOWNLOAD_DIALOG_CORNER_ALIGNMENT_BOTTOM_RIGHT);
		dualize(RETVAL, "COREWEBVIEW2_DEFAULT_DOWNLOAD_DIALOG_CORNER_ALIGNMENT_BOTTOM_RIGHT");
	OUTPUT:
		RETVAL

#
# PROCESS_KIND
#

SV*
PROCESS_KIND_BROWSER()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_PROCESS_KIND_BROWSER);
		dualize(RETVAL, "COREWEBVIEW2_PROCESS_KIND_BROWSER");
	OUTPUT:
		RETVAL

SV*
PROCESS_KIND_RENDERER()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_PROCESS_KIND_RENDERER);
		dualize(RETVAL, "COREWEBVIEW2_PROCESS_KIND_RENDERER");
	OUTPUT:
		RETVAL

SV*
PROCESS_KIND_UTILITY()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_PROCESS_KIND_UTILITY);
		dualize(RETVAL, "COREWEBVIEW2_PROCESS_KIND_UTILITY");
	OUTPUT:
		RETVAL

SV*
PROCESS_KIND_SANDBOX_HELPER()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_PROCESS_KIND_SANDBOX_HELPER);
		dualize(RETVAL, "COREWEBVIEW2_PROCESS_KIND_SANDBOX_HELPER");
	OUTPUT:
		RETVAL

SV*
PROCESS_KIND_GPU()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_PROCESS_KIND_GPU);
		dualize(RETVAL, "COREWEBVIEW2_PROCESS_KIND_GPU");
	OUTPUT:
		RETVAL

SV*
PROCESS_KIND_PPAPI_PLUGIN()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_PROCESS_KIND_PPAPI_PLUGIN);
		dualize(RETVAL, "COREWEBVIEW2_PROCESS_KIND_PPAPI_PLUGIN");
	OUTPUT:
		RETVAL

SV*
PROCESS_KIND_PPAPI_BROKER()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_PROCESS_KIND_PPAPI_BROKER);
		dualize(RETVAL, "COREWEBVIEW2_PROCESS_KIND_PPAPI_BROKER");
	OUTPUT:
		RETVAL

#
# PDF_TOOLBAR_ITEMS
#

SV*
PDF_TOOLBAR_ITEMS_NONE()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_PDF_TOOLBAR_ITEMS_NONE);
		dualize(RETVAL, "COREWEBVIEW2_PDF_TOOLBAR_ITEMS_NONE");
	OUTPUT:
		RETVAL

SV*
PDF_TOOLBAR_ITEMS_SAVE()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_PDF_TOOLBAR_ITEMS_SAVE);
		dualize(RETVAL, "COREWEBVIEW2_PDF_TOOLBAR_ITEMS_SAVE");
	OUTPUT:
		RETVAL

SV*
PDF_TOOLBAR_ITEMS_PRINT()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_PDF_TOOLBAR_ITEMS_PRINT);
		dualize(RETVAL, "COREWEBVIEW2_PDF_TOOLBAR_ITEMS_PRINT");
	OUTPUT:
		RETVAL

SV*
PDF_TOOLBAR_ITEMS_SAVE_AS()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_PDF_TOOLBAR_ITEMS_SAVE_AS);
		dualize(RETVAL, "COREWEBVIEW2_PDF_TOOLBAR_ITEMS_SAVE_AS");
	OUTPUT:
		RETVAL

SV*
PDF_TOOLBAR_ITEMS_ZOOM_IN()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_PDF_TOOLBAR_ITEMS_ZOOM_IN);
		dualize(RETVAL, "COREWEBVIEW2_PDF_TOOLBAR_ITEMS_ZOOM_IN");
	OUTPUT:
		RETVAL

SV*
PDF_TOOLBAR_ITEMS_ZOOM_OUT()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_PDF_TOOLBAR_ITEMS_ZOOM_OUT);
		dualize(RETVAL, "COREWEBVIEW2_PDF_TOOLBAR_ITEMS_ZOOM_OUT");
	OUTPUT:
		RETVAL

SV*
PDF_TOOLBAR_ITEMS_ROTATE()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_PDF_TOOLBAR_ITEMS_ROTATE);
		dualize(RETVAL, "COREWEBVIEW2_PDF_TOOLBAR_ITEMS_ROTATE");
	OUTPUT:
		RETVAL

SV*
PDF_TOOLBAR_ITEMS_FIT_PAGE()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_PDF_TOOLBAR_ITEMS_FIT_PAGE);
		dualize(RETVAL, "COREWEBVIEW2_PDF_TOOLBAR_ITEMS_FIT_PAGE");
	OUTPUT:
		RETVAL

SV*
PDF_TOOLBAR_ITEMS_PAGE_LAYOUT()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_PDF_TOOLBAR_ITEMS_PAGE_LAYOUT);
		dualize(RETVAL, "COREWEBVIEW2_PDF_TOOLBAR_ITEMS_PAGE_LAYOUT");
	OUTPUT:
		RETVAL

SV*
PDF_TOOLBAR_ITEMS_BOOKMARKS()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_PDF_TOOLBAR_ITEMS_BOOKMARKS);
		dualize(RETVAL, "COREWEBVIEW2_PDF_TOOLBAR_ITEMS_BOOKMARKS");
	OUTPUT:
		RETVAL

SV*
PDF_TOOLBAR_ITEMS_PAGE_SELECTOR()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_PDF_TOOLBAR_ITEMS_PAGE_SELECTOR);
		dualize(RETVAL, "COREWEBVIEW2_PDF_TOOLBAR_ITEMS_PAGE_SELECTOR");
	OUTPUT:
		RETVAL

SV*
PDF_TOOLBAR_ITEMS_SEARCH()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_PDF_TOOLBAR_ITEMS_SEARCH);
		dualize(RETVAL, "COREWEBVIEW2_PDF_TOOLBAR_ITEMS_SEARCH");
	OUTPUT:
		RETVAL

SV*
PDF_TOOLBAR_ITEMS_FULL_SCREEN()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_PDF_TOOLBAR_ITEMS_FULL_SCREEN);
		dualize(RETVAL, "COREWEBVIEW2_PDF_TOOLBAR_ITEMS_FULL_SCREEN");
	OUTPUT:
		RETVAL

SV*
PDF_TOOLBAR_ITEMS_MORE_SETTINGS()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_PDF_TOOLBAR_ITEMS_MORE_SETTINGS);
		dualize(RETVAL, "COREWEBVIEW2_PDF_TOOLBAR_ITEMS_MORE_SETTINGS");
	OUTPUT:
		RETVAL

#
# CONTEXT_MENU_TARGET_KIND
#

SV*
CONTEXT_MENU_TARGET_KIND_PAGE()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_CONTEXT_MENU_TARGET_KIND_PAGE);
		dualize(RETVAL, "COREWEBVIEW2_CONTEXT_MENU_TARGET_KIND_PAGE");
	OUTPUT:
		RETVAL

SV*
CONTEXT_MENU_TARGET_KIND_IMAGE()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_CONTEXT_MENU_TARGET_KIND_IMAGE);
		dualize(RETVAL, "COREWEBVIEW2_CONTEXT_MENU_TARGET_KIND_IMAGE");
	OUTPUT:
		RETVAL

SV*
CONTEXT_MENU_TARGET_KIND_SELECTED_TEXT()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_CONTEXT_MENU_TARGET_KIND_SELECTED_TEXT);
		dualize(RETVAL, "COREWEBVIEW2_CONTEXT_MENU_TARGET_KIND_SELECTED_TEXT");
	OUTPUT:
		RETVAL

SV*
CONTEXT_MENU_TARGET_KIND_AUDIO()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_CONTEXT_MENU_TARGET_KIND_AUDIO);
		dualize(RETVAL, "COREWEBVIEW2_CONTEXT_MENU_TARGET_KIND_AUDIO");
	OUTPUT:
		RETVAL

SV*
CONTEXT_MENU_TARGET_KIND_VIDEO()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_CONTEXT_MENU_TARGET_KIND_VIDEO);
		dualize(RETVAL, "COREWEBVIEW2_CONTEXT_MENU_TARGET_KIND_VIDEO");
	OUTPUT:
		RETVAL

#
# CONTEXT_MENU_ITEM_KIND
#

SV*
CONTEXT_MENU_ITEM_KIND_COMMAND()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_CONTEXT_MENU_ITEM_KIND_COMMAND);
		dualize(RETVAL, "COREWEBVIEW2_CONTEXT_MENU_ITEM_KIND_COMMAND");
	OUTPUT:
		RETVAL

SV*
CONTEXT_MENU_ITEM_KIND_CHECK_BOX()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_CONTEXT_MENU_ITEM_KIND_CHECK_BOX);
		dualize(RETVAL, "COREWEBVIEW2_CONTEXT_MENU_ITEM_KIND_CHECK_BOX");
	OUTPUT:
		RETVAL

SV*
CONTEXT_MENU_ITEM_KIND_RADIO()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_CONTEXT_MENU_ITEM_KIND_RADIO);
		dualize(RETVAL, "COREWEBVIEW2_CONTEXT_MENU_ITEM_KIND_RADIO");
	OUTPUT:
		RETVAL

SV*
CONTEXT_MENU_ITEM_KIND_SEPARATOR()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_CONTEXT_MENU_ITEM_KIND_SEPARATOR);
		dualize(RETVAL, "COREWEBVIEW2_CONTEXT_MENU_ITEM_KIND_SEPARATOR");
	OUTPUT:
		RETVAL

SV*
CONTEXT_MENU_ITEM_KIND_SUBMENU()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_CONTEXT_MENU_ITEM_KIND_SUBMENU);
		dualize(RETVAL, "COREWEBVIEW2_CONTEXT_MENU_ITEM_KIND_SUBMENU");
	OUTPUT:
		RETVAL

#
# PREFERRED_COLOR_SCHEME
#

SV*
PREFERRED_COLOR_SCHEME_AUTO()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_PREFERRED_COLOR_SCHEME_AUTO);
		dualize(RETVAL, "COREWEBVIEW2_PREFERRED_COLOR_SCHEME_AUTO");
	OUTPUT:
		RETVAL

SV*
PREFERRED_COLOR_SCHEME_LIGHT()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_PREFERRED_COLOR_SCHEME_LIGHT);
		dualize(RETVAL, "COREWEBVIEW2_PREFERRED_COLOR_SCHEME_LIGHT");
	OUTPUT:
		RETVAL

SV*
PREFERRED_COLOR_SCHEME_DARK()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_PREFERRED_COLOR_SCHEME_DARK);
		dualize(RETVAL, "COREWEBVIEW2_PREFERRED_COLOR_SCHEME_DARK");
	OUTPUT:
		RETVAL

#
# BROWSING_DATA_KINDS
#

SV*
BROWSING_DATA_KINDS_FILE_SYSTEMS()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_BROWSING_DATA_KINDS_FILE_SYSTEMS);
		dualize(RETVAL, "COREWEBVIEW2_BROWSING_DATA_KINDS_FILE_SYSTEMS");
	OUTPUT:
		RETVAL

SV*
BROWSING_DATA_KINDS_INDEXED_DB()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_BROWSING_DATA_KINDS_INDEXED_DB);
		dualize(RETVAL, "COREWEBVIEW2_BROWSING_DATA_KINDS_INDEXED_DB");
	OUTPUT:
		RETVAL

SV*
BROWSING_DATA_KINDS_LOCAL_STORAGE()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_BROWSING_DATA_KINDS_LOCAL_STORAGE);
		dualize(RETVAL, "COREWEBVIEW2_BROWSING_DATA_KINDS_LOCAL_STORAGE");
	OUTPUT:
		RETVAL

SV*
BROWSING_DATA_KINDS_WEB_SQL()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_BROWSING_DATA_KINDS_WEB_SQL);
		dualize(RETVAL, "COREWEBVIEW2_BROWSING_DATA_KINDS_WEB_SQL");
	OUTPUT:
		RETVAL

SV*
BROWSING_DATA_KINDS_CACHE_STORAGE()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_BROWSING_DATA_KINDS_CACHE_STORAGE);
		dualize(RETVAL, "COREWEBVIEW2_BROWSING_DATA_KINDS_CACHE_STORAGE");
	OUTPUT:
		RETVAL

SV*
BROWSING_DATA_KINDS_ALL_DOM_STORAGE()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_BROWSING_DATA_KINDS_ALL_DOM_STORAGE);
		dualize(RETVAL, "COREWEBVIEW2_BROWSING_DATA_KINDS_ALL_DOM_STORAGE");
	OUTPUT:
		RETVAL

SV*
BROWSING_DATA_KINDS_COOKIES()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_BROWSING_DATA_KINDS_COOKIES);
		dualize(RETVAL, "COREWEBVIEW2_BROWSING_DATA_KINDS_COOKIES");
	OUTPUT:
		RETVAL

SV*
BROWSING_DATA_KINDS_ALL_SITE()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_BROWSING_DATA_KINDS_ALL_SITE);
		dualize(RETVAL, "COREWEBVIEW2_BROWSING_DATA_KINDS_ALL_SITE");
	OUTPUT:
		RETVAL

SV*
BROWSING_DATA_KINDS_DISK_CACHE()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_BROWSING_DATA_KINDS_DISK_CACHE);
		dualize(RETVAL, "COREWEBVIEW2_BROWSING_DATA_KINDS_DISK_CACHE");
	OUTPUT:
		RETVAL

SV*
BROWSING_DATA_KINDS_DOWNLOAD_HISTORY()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_BROWSING_DATA_KINDS_DOWNLOAD_HISTORY);
		dualize(RETVAL, "COREWEBVIEW2_BROWSING_DATA_KINDS_DOWNLOAD_HISTORY");
	OUTPUT:
		RETVAL

SV*
BROWSING_DATA_KINDS_GENERAL_AUTOFILL()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_BROWSING_DATA_KINDS_GENERAL_AUTOFILL);
		dualize(RETVAL, "COREWEBVIEW2_BROWSING_DATA_KINDS_GENERAL_AUTOFILL");
	OUTPUT:
		RETVAL

SV*
BROWSING_DATA_KINDS_PASSWORD_AUTOSAVE()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_BROWSING_DATA_KINDS_PASSWORD_AUTOSAVE);
		dualize(RETVAL, "COREWEBVIEW2_BROWSING_DATA_KINDS_PASSWORD_AUTOSAVE");
	OUTPUT:
		RETVAL

SV*
BROWSING_DATA_KINDS_BROWSING_HISTORY()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_BROWSING_DATA_KINDS_BROWSING_HISTORY);
		dualize(RETVAL, "COREWEBVIEW2_BROWSING_DATA_KINDS_BROWSING_HISTORY");
	OUTPUT:
		RETVAL

SV*
BROWSING_DATA_KINDS_SETTINGS()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_BROWSING_DATA_KINDS_SETTINGS);
		dualize(RETVAL, "COREWEBVIEW2_BROWSING_DATA_KINDS_SETTINGS");
	OUTPUT:
		RETVAL

SV*
BROWSING_DATA_KINDS_ALL_PROFILE()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_BROWSING_DATA_KINDS_ALL_PROFILE);
		dualize(RETVAL, "COREWEBVIEW2_BROWSING_DATA_KINDS_ALL_PROFILE");
	OUTPUT:
		RETVAL

SV*
BROWSING_DATA_KINDS_SERVICE_WORKERS()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_BROWSING_DATA_KINDS_SERVICE_WORKERS);
		dualize(RETVAL, "COREWEBVIEW2_BROWSING_DATA_KINDS_SERVICE_WORKERS");
	OUTPUT:
		RETVAL

#
# SERVER_CERTIFICATE_ERROR_ACTION
#

SV*
SERVER_CERTIFICATE_ERROR_ACTION_ALWAYS_ALLOW()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_SERVER_CERTIFICATE_ERROR_ACTION_ALWAYS_ALLOW);
		dualize(RETVAL, "COREWEBVIEW2_SERVER_CERTIFICATE_ERROR_ACTION_ALWAYS_ALLOW");
	OUTPUT:
		RETVAL

SV*
SERVER_CERTIFICATE_ERROR_ACTION_CANCEL()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_SERVER_CERTIFICATE_ERROR_ACTION_CANCEL);
		dualize(RETVAL, "COREWEBVIEW2_SERVER_CERTIFICATE_ERROR_ACTION_CANCEL");
	OUTPUT:
		RETVAL

SV*
SERVER_CERTIFICATE_ERROR_ACTION_DEFAULT()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_SERVER_CERTIFICATE_ERROR_ACTION_DEFAULT);
		dualize(RETVAL, "COREWEBVIEW2_SERVER_CERTIFICATE_ERROR_ACTION_DEFAULT");
	OUTPUT:
		RETVAL

#
# FAVICON_IMAGE_FORMAT
#

SV*
FAVICON_IMAGE_FORMAT_PNG()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_FAVICON_IMAGE_FORMAT_PNG);
		dualize(RETVAL, "COREWEBVIEW2_FAVICON_IMAGE_FORMAT_PNG");
	OUTPUT:
		RETVAL

SV*
FAVICON_IMAGE_FORMAT_JPEG()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_FAVICON_IMAGE_FORMAT_JPEG);
		dualize(RETVAL, "COREWEBVIEW2_FAVICON_IMAGE_FORMAT_JPEG");
	OUTPUT:
		RETVAL

#
# PRINT_DIALOG_KIND
#

SV*
PRINT_DIALOG_KIND_BROWSER()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_PRINT_DIALOG_KIND_BROWSER);
		dualize(RETVAL, "COREWEBVIEW2_PRINT_DIALOG_KIND_BROWSER");
	OUTPUT:
		RETVAL

SV*
PRINT_DIALOG_KIND_SYSTEM()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_PRINT_DIALOG_KIND_SYSTEM);
		dualize(RETVAL, "COREWEBVIEW2_PRINT_DIALOG_KIND_SYSTEM");
	OUTPUT:
		RETVAL

#
# PRINT_DUPLEX
#

SV*
PRINT_DUPLEX_DEFAULT()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_PRINT_DUPLEX_DEFAULT);
		dualize(RETVAL, "COREWEBVIEW2_PRINT_DUPLEX_DEFAULT");
	OUTPUT:
		RETVAL

SV*
PRINT_DUPLEX_ONE_SIDED()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_PRINT_DUPLEX_ONE_SIDED);
		dualize(RETVAL, "COREWEBVIEW2_PRINT_DUPLEX_ONE_SIDED");
	OUTPUT:
		RETVAL

SV*
PRINT_DUPLEX_TWO_SIDED_LONG_EDGE()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_PRINT_DUPLEX_TWO_SIDED_LONG_EDGE);
		dualize(RETVAL, "COREWEBVIEW2_PRINT_DUPLEX_TWO_SIDED_LONG_EDGE");
	OUTPUT:
		RETVAL

SV*
PRINT_DUPLEX_TWO_SIDED_SHORT_EDGE()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_PRINT_DUPLEX_TWO_SIDED_SHORT_EDGE);
		dualize(RETVAL, "COREWEBVIEW2_PRINT_DUPLEX_TWO_SIDED_SHORT_EDGE");
	OUTPUT:
		RETVAL

#
# PRINT_COLOR_MODE
#

SV*
PRINT_COLOR_MODE_DEFAULT()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_PRINT_COLOR_MODE_DEFAULT);
		dualize(RETVAL, "COREWEBVIEW2_PRINT_COLOR_MODE_DEFAULT");
	OUTPUT:
		RETVAL

SV*
PRINT_COLOR_MODE_COLOR()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_PRINT_COLOR_MODE_COLOR);
		dualize(RETVAL, "COREWEBVIEW2_PRINT_COLOR_MODE_COLOR");
	OUTPUT:
		RETVAL

SV*
PRINT_COLOR_MODE_GRAYSCALE()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_PRINT_COLOR_MODE_GRAYSCALE);
		dualize(RETVAL, "COREWEBVIEW2_PRINT_COLOR_MODE_GRAYSCALE");
	OUTPUT:
		RETVAL

#
# PRINT_COLLATION
#

SV*
PRINT_COLLATION_DEFAULT()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_PRINT_COLLATION_DEFAULT);
		dualize(RETVAL, "COREWEBVIEW2_PRINT_COLLATION_DEFAULT");
	OUTPUT:
		RETVAL

SV*
PRINT_COLLATION_COLLATED()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_PRINT_COLLATION_COLLATED);
		dualize(RETVAL, "COREWEBVIEW2_PRINT_COLLATION_COLLATED");
	OUTPUT:
		RETVAL

SV*
PRINT_COLLATION_UNCOLLATED()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_PRINT_COLLATION_UNCOLLATED);
		dualize(RETVAL, "COREWEBVIEW2_PRINT_COLLATION_UNCOLLATED");
	OUTPUT:
		RETVAL

#
# PRINT_MEDIA_SIZE
#

SV*
PRINT_MEDIA_SIZE_DEFAULT()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_PRINT_MEDIA_SIZE_DEFAULT);
		dualize(RETVAL, "COREWEBVIEW2_PRINT_MEDIA_SIZE_DEFAULT");
	OUTPUT:
		RETVAL

SV*
PRINT_MEDIA_SIZE_CUSTOM()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_PRINT_MEDIA_SIZE_CUSTOM);
		dualize(RETVAL, "COREWEBVIEW2_PRINT_MEDIA_SIZE_CUSTOM");
	OUTPUT:
		RETVAL

#
# PRINT_STATUS
#

SV*
PRINT_STATUS_SUCCEEDED()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_PRINT_STATUS_SUCCEEDED);
		dualize(RETVAL, "COREWEBVIEW2_PRINT_STATUS_SUCCEEDED");
	OUTPUT:
		RETVAL

SV*
PRINT_STATUS_PRINTER_UNAVAILABLE()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_PRINT_STATUS_PRINTER_UNAVAILABLE);
		dualize(RETVAL, "COREWEBVIEW2_PRINT_STATUS_PRINTER_UNAVAILABLE");
	OUTPUT:
		RETVAL

SV*
PRINT_STATUS_OTHER_ERROR()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_PRINT_STATUS_OTHER_ERROR);
		dualize(RETVAL, "COREWEBVIEW2_PRINT_STATUS_OTHER_ERROR");
	OUTPUT:
		RETVAL

#
# TRACKING_PREVENTION_LEVEL
#

SV*
TRACKING_PREVENTION_LEVEL_NONE()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_TRACKING_PREVENTION_LEVEL_NONE);
		dualize(RETVAL, "COREWEBVIEW2_TRACKING_PREVENTION_LEVEL_NONE");
	OUTPUT:
		RETVAL

SV*
TRACKING_PREVENTION_LEVEL_BASIC()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_TRACKING_PREVENTION_LEVEL_BASIC);
		dualize(RETVAL, "COREWEBVIEW2_TRACKING_PREVENTION_LEVEL_BASIC");
	OUTPUT:
		RETVAL

SV*
TRACKING_PREVENTION_LEVEL_BALANCED()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_TRACKING_PREVENTION_LEVEL_BALANCED);
		dualize(RETVAL, "COREWEBVIEW2_TRACKING_PREVENTION_LEVEL_BALANCED");
	OUTPUT:
		RETVAL

SV*
TRACKING_PREVENTION_LEVEL_STRICT()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_TRACKING_PREVENTION_LEVEL_STRICT);
		dualize(RETVAL, "COREWEBVIEW2_TRACKING_PREVENTION_LEVEL_STRICT");
	OUTPUT:
		RETVAL

#
# SHARED_BUFFER_ACCESS
#

SV*
SHARED_BUFFER_ACCESS_READ_ONLY()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_SHARED_BUFFER_ACCESS_READ_ONLY);
		dualize(RETVAL, "COREWEBVIEW2_SHARED_BUFFER_ACCESS_READ_ONLY");
	OUTPUT:
		RETVAL

SV*
SHARED_BUFFER_ACCESS_READ_WRITE()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_SHARED_BUFFER_ACCESS_READ_WRITE);
		dualize(RETVAL, "COREWEBVIEW2_SHARED_BUFFER_ACCESS_READ_WRITE");
	OUTPUT:
		RETVAL

#
# MEMORY_USAGE_TARGET_LEVEL
#

SV*
MEMORY_USAGE_TARGET_LEVEL_NORMAL()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_MEMORY_USAGE_TARGET_LEVEL_NORMAL);
		dualize(RETVAL, "COREWEBVIEW2_MEMORY_USAGE_TARGET_LEVEL_NORMAL");
	OUTPUT:
		RETVAL

SV*
MEMORY_USAGE_TARGET_LEVEL_LOW()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_MEMORY_USAGE_TARGET_LEVEL_LOW);
		dualize(RETVAL, "COREWEBVIEW2_MEMORY_USAGE_TARGET_LEVEL_LOW");
	OUTPUT:
		RETVAL

#
# NAVIGATION_KIND
#

SV*
NAVIGATION_KIND_RELOAD()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_NAVIGATION_KIND_RELOAD);
		dualize(RETVAL, "COREWEBVIEW2_NAVIGATION_KIND_RELOAD");
	OUTPUT:
		RETVAL

SV*
NAVIGATION_KIND_BACK_OR_FORWARD()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_NAVIGATION_KIND_BACK_OR_FORWARD);
		dualize(RETVAL, "COREWEBVIEW2_NAVIGATION_KIND_BACK_OR_FORWARD");
	OUTPUT:
		RETVAL

SV*
NAVIGATION_KIND_NEW_DOCUMENT()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_NAVIGATION_KIND_NEW_DOCUMENT);
		dualize(RETVAL, "COREWEBVIEW2_NAVIGATION_KIND_NEW_DOCUMENT");
	OUTPUT:
		RETVAL

#
# FRAME_KIND
#

SV*
FRAME_KIND_UNKNOWN()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_FRAME_KIND_UNKNOWN);
		dualize(RETVAL, "COREWEBVIEW2_FRAME_KIND_UNKNOWN");
	OUTPUT:
		RETVAL

SV*
FRAME_KIND_MAIN_FRAME()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_FRAME_KIND_MAIN_FRAME);
		dualize(RETVAL, "COREWEBVIEW2_FRAME_KIND_MAIN_FRAME");
	OUTPUT:
		RETVAL

SV*
FRAME_KIND_IFRAME()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_FRAME_KIND_IFRAME);
		dualize(RETVAL, "COREWEBVIEW2_FRAME_KIND_IFRAME");
	OUTPUT:
		RETVAL

SV*
FRAME_KIND_EMBED()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_FRAME_KIND_EMBED);
		dualize(RETVAL, "COREWEBVIEW2_FRAME_KIND_EMBED");
	OUTPUT:
		RETVAL

SV*
FRAME_KIND_OBJECT()
	CODE:
		RETVAL = newSVuv((UV)COREWEBVIEW2_FRAME_KIND_OBJECT);
		dualize(RETVAL, "COREWEBVIEW2_FRAME_KIND_OBJECT");
	OUTPUT:
		RETVAL

