=pod

=head1 NAME

CoreWebView2::DownloadStartingEventArgs

=head1 VERSION

0.001.000

=head1 SYNOPSIS

TBD

=head1 DESCRIPTION

TBD

=head1 METHODS

=head2 GetDeferral

    $deferral = $object->GetDeferral();

Returns a L<CoreWebView2::Deferral> object

See L<https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2downloadstartingeventargs#getdeferral>.

=head1 PROPERTIES

=head2 Cancel

    $cancel = $object->get_Cancel();
    $object->put_Cancel($cancel);

A boolean.

See L<https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2downloadstartingeventargs#get_cancel>, L<https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2downloadstartingeventargs#put_cancel>.

=head2 DownloadOperation

    $downloadOperation = $object->get_DownloadOperation();

A L<CoreWebView2::DownloadOperation> object.

See L<https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2downloadstartingeventargs#get_downloadoperation>.

=head2 Handled

    $handled = $object->get_Handled();
    $object->put_Handled($handled);

A boolean.

See L<https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2downloadstartingeventargs#get_handled>, L<https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2downloadstartingeventargs#put_handled>.

=head2 ResultFilePath

    $resultFilePath = $object->get_ResultFilePath();
    $object->put_ResultFilePath($resultFilePath);

A string.

See L<https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2downloadstartingeventargs#get_resultfilepath>, L<https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2downloadstartingeventargs#put_resultfilepath>.

=cut
