=pod

=head1 NAME

CoreWebView2::FrameCreatedEventArgs

=head1 VERSION

0.001.000

=head1 SYNOPSIS

TBD

=head1 DESCRIPTION

TBD

=head1 METHODS

=head1 PROPERTIES

=head2 Frame

    $frame = $object->get_Frame();

A L<CoreWebView2::Frame> object.

See L<https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2framecreatedeventargs#get_frame>.

=cut
