=pod

=head1 NAME

CoreWebView2::WebResourceResponseView

=head1 VERSION

0.001.000

=head1 SYNOPSIS

TBD

=head1 DESCRIPTION

TBD

=head1 METHODS

=head2 GetContent

    $result = $object->GetContent($handler);

Takes

=over

=item * $handler: event handler object

=back

Returns a L<HRESULT|CoreWebView2::constants/HRESULT> constant

Triggers L</WebResourceResponseViewGetContentCompleted>

See L<https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2webresourceresponseview#getcontent>.

=head1 PROPERTIES

=head2 Headers

    $headers = $object->get_Headers();

A L<CoreWebView2::HttpResponseHeaders> object.

See L<https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2webresourceresponseview#get_headers>.

=head2 ReasonPhrase

    $reasonPhrase = $object->get_ReasonPhrase();

A string.

See L<https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2webresourceresponseview#get_reasonphrase>.

=head2 StatusCode

    $statusCode = $object->get_StatusCode();

An integer.

See L<https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2webresourceresponseview#get_statuscode>.

=head1 EVENTS

=head2 WebResourceResponseViewGetContentCompleted

    $result = $object->GetContent(...);

    # in handler class
    sub WebResourceResponseViewGetContentCompleted {
        my ($self, $errorCode, $content) = @_;

        # handle the event here
    }

See L</GetContent>.

Passes

=over

=item * $errorCode: L<HRESULT|CoreWebView2::constants/HRESULT> constant

=item * $content: stream

=back

=cut
